---
title: "Q2_7"
author: "Kamin Atsavasirilert"
date: "2023-12-03"
output: html_document
---

```{r setup, include=FALSE}
```

## Q2.7 Week 13

```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
library(quantmod)
library(fGarch)


getSymbols(Symbols = "^GSPC", from = "2000-01-01", to = "2022-11-12", auto_assign = TRUE)
return=dailyReturn(GSPC,type="log")
return
length(return)
length(return[!is.infinite(return)])

x = 1
y = 1
m = 2
n = 2

cat("ARMA(", x, ", ", y, ") with GARCH(", m, ", ", n, ")")

result = garchFit(formula = substitute(~arma(p,q)+garch(i,j),
                                    list(p=x,
                                         q=y,
                                         i=m,
                                         j=n)), 
               data = coredata(return), 
               cond.dist = "sged")
cat("AIC: ", result@fit$ics[1]*nrow(return))

res = residuals(result, standardize=T)
qqplot(res,rsged(10000,nu=1.368868,xi=8.561305e-01))
qqline(res)
```
