---
title: "Q1_2"
author: "Kamin Atsavasirilert"
date: "2023-09-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Q1.2 week 5

when increases n by 4 times, the sample standard deviations of the payoffs did not decrease by 2 times

```{r cars}
#parameters
t = 1
rf = 0.01
rho = 0.1
K = 250

s10 = 100
q1 = 0.00
vol1 = 0.5
s20 = 150
q2 = 0.03
vol2 = 0.4

mu1 = log(s10) + (rf - q1 - 0.5 * vol1^2) * t
mu2 = log(s20) + (rf - q2 - 0.5 * vol2^2) * t

num_trial = 40000
for (num_trial in c(10000,40000)){

  basket_call_val = 0
  basket_call_val_sqr = 0
  
  for (i in 1:num_trial) {
    z1 = rnorm(1, mean = 0, sd = 1)
    s11 = exp(mu1 + vol1 * sqrt(t) * z1)
    
    tmp_z2 = rnorm(1, mean = 0, sd = 1)
    z2 = rho * z1 + sqrt(1 - rho^2) * tmp_z2
    s21 = exp(mu2 + vol2 * sqrt(t) * z2)
    total_price = s11 + s21
    
    disc_tmp_payoff = max(0, total_price - K) * exp(-rf * t)
    basket_call_val = ((i - 1) * basket_call_val + disc_tmp_payoff) / i
    basket_call_val_sqr = ((i - 1) * basket_call_val_sqr + disc_tmp_payoff^2) / i
  }
  
  sample_std_x =  sqrt((basket_call_val_sqr - basket_call_val^2) * i /(i - 1))
  
  cat("with n = ", num_trial," the sample_std_of_the_payoffs =", sample_std_x, "\n")
  
}

```
